### ISSUE TITLE
Plugin stopped working after upgrading tmux to 3.2

### ISSUE THREAD

**Issue by manskron** [junegunn/tmux-fzf-maccy#2]
If I run the fzf-maccy.sh script directly, everything seems to work fine. fzf shows up in a bottom split.
But the keybinding doesn't seem to work. I've tried binding it to a custom key as well.

Platform: Mac
Terminal: Kitty
Tmux version: 3.2
Shell: zsh

**Comment by junegunn** [comment]
Do you have the latest version of fzf and fzf-tmux? You should see a popup window when you run `fzf-tmux -p`.

**Comment by manskron** [comment]
Upgrading `fzf` solved it. Thought I was on the latest version. 
Sorry about that and thanks for the help.
